### ISSUE TITLE
VM Freeze

### ISSUE THREAD

**Issue by vialorn** [postgres-ai/database-lab#2]
After some time of running up, Hyper-V VM starts up consuming CPU ("sy" around 90-100%), then it takes up to a few minutes to (re)start sync-instance container. Finally, VM hangs on completely; it may be impossible to restart/stop VM via Hyper-V commands.

VM specs:
- 10 GB RAM
- 2 vCPU (Yeap, it's just a sandbox, I want to master this tool)
- 32 GB system disk (VHDX over SATA SSD)
- 500 GB ZFS disk (VHDX over SATA HDD)
- Ubuntu 20.04 LTS (just Docker & ZFS & Database Lab & VS Code installed by its Windows UI).

Host specs:
- 64 GB RAM
- Core i5 6400
- Windows 10 Pro 20H2 & Hyper-V.

As it was last time:
![Снимок экрана 2020-12-06 180828](https://user-images.githubusercontent.com/5932932/101283836-18a2d200-37ee-11eb-8be9-2c0c4a39433a.png)

**Comment by NikolayS** [comment]
@vialorn this is a very unusual setup that no one tried for Database Lab so far (as I know) - a VM running on Windows. Are you planning to use it for real-life case or you used it just to get Linux to explore Database Lab features?

**Comment by vialorn** [comment]
@NikolayS , Windows host is just to try and explore. I have no other sandbox host machine, but I want to become familiar with Database Lab before I can actively recommend it to my company. BTW Hyper-V has shown itself as a good solution for any other sandbox activity for far, e.g. VMs with PostgreSQL and Clickhouse databases about 10-40 GB.

**Comment by agneum** [comment]
@vialorn, it seems there are some errors related to mounting directories in the VM. 
Could you please provide the logs of the Database Lab Engine container?

**Comment by vialorn** [comment]
It seems I made an error on some iteration of custom (PostgrePRO) image development by not cleaning up all the things. After repeating "from scratch," VM seems to work fine.
